#!/bin/sh

set -eu

juju-log 'Invoking charm-pre-install hooks'
[ -d exec.d ] && ( for f in exec.d/*/charm-pre-install; do [ -x $f ] && /bin/sh -c "$f"; done )

juju-log 'Ensuring python, python-apt and python-yaml are installed'
apt-get install -y python python-apt python-yaml

juju-log 'Invoking python-based install hook'
python hooks/hooks.py install
