#!/bin/sh

set -eu

juju-log 'Invoking charm-pre-install hooks'
[ -d exec.d ] && ( for f in exec.d/*/charm-pre-install; do [ -x $f ] && /bin/sh -c "$f"; done )

DISTRIB_CODENAME=$(grep DISTRIB_CODENAME /etc/lsb-release | cut -d= -f2)
if [ "${DISTRIB_CODENAME}" = "focal" ]; then
    juju-log 'Ensuring python2, python-apt and python-yaml are installed'
    apt-get install -y python2 python-apt python-yaml

    juju-log 'Invoking python2-based install hook'
    python2 hooks/hooks.py install
else
    juju-log 'Ensuring python, python-apt and python-yaml are installed'
    apt-get install -y python python-apt python-yaml

    juju-log 'Invoking python-based install hook'
    python hooks/hooks.py install
fi
